backend:
  name: git-gateway
  branch: panel
  login: true

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "cardapio"
    label: "Cardápio"
    files:
      - file: "data/cardapio.json"
        label: "Pratos"
        name: "pratos"
        fields:
          - label: "Itens"
            name: "itens"
            widget: "list"
            fields:
              - { label: "Nome", name: "nome", widget: "string" }
              - { label: "Preço", name: "preco", widget: "string" }
              - { label: "Descrição", name: "descricao", widget: "text" }
              - { label: "Imagem", name: "imagem", widget: "image" }
  - name: "destaque"
    label: "Prato em Destaque"
    files:
      - file: "data/destaque.json"
        label: "Bloco de Destaque (Home)"
        name: "destaque_home"
        fields:
          - { label: "Título", name: "titulo", widget: "string" }
          - { label: "Nome do prato", name: "nome", widget: "string" }
          - { label: "Link do botão", name: "link", widget: "string" }
          - { label: "Texto do botão", name: "botao", widget: "string" }
