backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "cardapio"
    label: "Cardápio"
    folder: "content/cardapio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome do prato", name: "nome", widget: "string" }
      - { label: "Preço", name: "preco", widget: "string" }
      - { label: "Descrição", name: "descricao", widget: "text" }
      - { label: "Imagem", name: "imagem", widget: "image" }
